---
- name: 'cleanup | Ensure downloaded ISO is removed: {{ __iso_path }}'
  ansible.builtin.file:
    path: '{{ __iso_path }}'
    state: 'absent'
  become: true
  when: >
    _cleanup_iso is defined
    and _cleanup_iso

- name: 'cleanup | Ensure temporary work directory is removed: {{ _temporary_work_dir_path }}'
  ansible.builtin.file:
    path: '{{ _temporary_work_dir_path }}'
    state: 'absent'
  become: true
  when: >
    _cleanup_work_dir is defined
    and _cleanup_work_dir
...
